# Generated by Django 5.2.8 on 2025-11-18 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Ej: PVF, NTG', max_length=10, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pertenencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('grupo', models.ForeignKey(help_text='Rol en esta empresa', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertenencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso de Usuario',
                'verbose_name_plural': 'Accesos de Usuarios',
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
