# Generated by Django 5.2.8 on 2025-11-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'permissions': [('acceso_modulo_compras', 'Puede acceder al Módulo de Compras'), ('acceso_modulo_inventario', 'Puede acceder al Módulo de Inventario')]},
        ),
    ]
