# Generated by Django 5.2.8 on 2025-11-18 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_empresa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'permissions': [('inventario_acceso', 'INVENTARIO: Ingreso al módulo (Portero)'), ('inventario_ver_movimiento', 'INVENTARIO: Ver detalles y stock'), ('inventario_crear_movimiento', 'INVENTARIO: Crear nuevos ingresos/egresos'), ('inventario_editar_movimiento', 'INVENTARIO: Editar movimientos (Solo borradores)'), ('inventario_anular_movimiento', 'INVENTARIO: Puede ANULAR un movimiento procesado'), ('inventario_procesos_criticos', 'INVENTARIO: Recálculo de costos y cierres'), ('compras_acceso', 'COMPRAS: Ingreso al módulo'), ('compras_crear_orden', 'COMPRAS: Crear solicitudes y órdenes'), ('compras_aprobar_orden', 'COMPRAS: Aprobar órdenes (Jefaturas)'), ('compras_ver_reportes', 'COMPRAS: Ver reportes financieros'), ('contabilidad_acceso', 'CONTABILIDAD: Ingreso al módulo'), ('contabilidad_gestion', 'CONTABILIDAD: Asientos y procesos operativos'), ('contabilidad_auditoria', 'CONTABILIDAD: Solo lectura (Auditores)'), ('chatbot_acceso', 'CHATBOT: Acceso para interactuar'), ('chatbot_admin', 'CHATBOT: Ver logs y entrenar'), ('sistema_gestion_usuarios', 'SISTEMA: Puede crear usuarios y asignar roles')]},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desactivar para impedir nuevos accesos a esta empresa sin borrar datos.'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(help_text='Código interno único (Ej: PVF, NTG)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pertenencia',
            name='grupo',
            field=models.ForeignKey(help_text='El Rol (Grupo de permisos) que ejerce el usuario en esta empresa.', on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
