# Generated by Django 5.2.8 on 2025-11-18 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_alter_empresa_options_alter_empresa_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Ej: FIN, LOG, IT', max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'permissions': [('inventario_acceso', 'INVENTARIO: Ingreso al módulo'), ('inventario_ver_movimiento', 'INVENTARIO: Ver detalles y stock'), ('inventario_crear_movimiento', 'INVENTARIO: Crear ingresos/egresos'), ('inventario_editar_movimiento', 'INVENTARIO: Editar borradores'), ('inventario_anular_movimiento', 'INVENTARIO: 🔴 ANULAR movimientos'), ('inventario_procesos_criticos', 'INVENTARIO: Recálculo de costos'), ('compras_acceso', 'COMPRAS: Ingreso al módulo'), ('compras_crear_orden', 'COMPRAS: Crear órdenes'), ('compras_aprobar_orden', 'COMPRAS: ✅ Aprobar órdenes'), ('compras_ver_reportes', 'COMPRAS: Ver reportes financieros'), ('dispensario_acceso', 'DISPENSARIO: Ingreso al módulo'), ('dispensario_ver_pacientes', 'DISPENSARIO: Ver historial médico'), ('sistema_gestion_usuarios', 'SISTEMA: Gestión de usuarios')]},
        ),
        migrations.AlterModelOptions(
            name='pertenencia',
            options={'verbose_name': 'Asignación de Rol', 'verbose_name_plural': 'Asignaciones de Roles'},
        ),
        migrations.AddField(
            model_name='pertenencia',
            name='permisos_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Excepciones específicas para este usuario en esta empresa.', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='pertenencia',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='pertenencia',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.area'),
        ),
        migrations.CreateModel(
            name='HistorialCambiosRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_actor', to=settings.AUTH_USER_MODEL)),
                ('usuario_afectado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_afectado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_gerencial', models.BooleanField(default=False, help_text='Si es True, este rol puede gestionar a otros.')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='auth.group')),
            ],
        ),
    ]
