# Generated by Django 5.2.8 on 2025-11-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_area_alter_empresa_options_alter_pertenencia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('chatbot_acceso', 'CHATBOT: Acceso para interactuar'), ('chatbot_admin', 'CHATBOT: Ver logs y entrenar')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ModuloCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('compras_acceso', 'COMPRAS: Ingreso al módulo'), ('compras_crear_orden', 'COMPRAS: Crear órdenes'), ('compras_aprobar_orden', 'COMPRAS: ✅ Aprobar órdenes (Jefatura)'), ('compras_ver_reportes', 'COMPRAS: Ver reportes financieros')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ModuloInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('inventario_acceso', 'INVENTARIO: Ingreso al módulo'), ('inventario_ver_movimiento', 'INVENTARIO: Ver detalles y stock'), ('inventario_crear_movimiento', 'INVENTARIO: Crear ingresos/egresos'), ('inventario_editar_movimiento', 'INVENTARIO: Editar borradores'), ('inventario_anular_movimiento', 'INVENTARIO: 🔴 ANULAR movimientos'), ('inventario_procesos_criticos', 'INVENTARIO: Recálculo de costos')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('sistema_gestion_usuarios', 'SISTEMA: Gestión de usuarios'), ('dispensario_acceso', 'DISPENSARIO: Ingreso al módulo'), ('dispensario_ver_pacientes', 'DISPENSARIO: Ver historial médico')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
    ]
