# Generated by Django 5.2.8 on 2025-11-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modulochatbot_modulocompras_moduloinventario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuloInventario',
        ),
        migrations.AlterModelOptions(
            name='modulocompras',
            options={'default_permissions': (), 'managed': False, 'permissions': [('compras_acceso', 'COMPRAS: Ingreso al módulo'), ('compras_crear_orden', 'COMPRAS: Crear órdenes'), ('compras_aprobar_orden', 'COMPRAS: Aprobar órdenes (Jefatura)'), ('compras_ver_reportes', 'COMPRAS: Ver reportes financieros')]},
        ),
        migrations.AlterModelOptions(
            name='modulosistema',
            options={'default_permissions': (), 'managed': False, 'permissions': [('sistema_gestion_usuarios', 'SISTEMA: Gestión de usuarios')]},
        ),
    ]
